kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-for-pods
spec:
  accessModes:
    - ReadOnlyMany
    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
