apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: userClusterRoleBinding
subjects:
- kind: User
  name: newUser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: userClusterRoleDef
  apiGroup: rbac.authorization.k8s.io

